# Generated by Django 5.2.7 on 2025-10-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField()),
                ('t', models.IntegerField()),
                ('iso_utc', models.DateTimeField()),
                ('iso_ny', models.DateTimeField()),
                ('o', models.FloatField()),
                ('h', models.FloatField()),
                ('l', models.FloatField()),
                ('c', models.FloatField()),
                ('v', models.IntegerField()),
                ('vw', models.FloatField()),
                ('n', models.IntegerField()),
                ('span', models.CharField()),
                ('vola', models.FloatField()),
            ],
        ),
    ]
