# Generated by Django 5.2.7 on 2025-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='vola',
            field=models.FloatField(null=True),
        ),
    ]
