# Generated by Django 5.2.7 on 2025-10-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingest', '0002_alter_case_vola'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='s',
            field=models.FloatField(null=True),
        ),
    ]
