# Generated by Django 5.2.7 on 2025-10-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ingest', '0005_prediction_predictionmeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='s',
            new_name='risk',
        ),
    ]
